import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

const jetBrains = JetBrains_Mono({ 
  weight: ['400', '700'],
  subsets: ["latin"] })

export const metadata = {
  title: "Anton D - Front end Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-fulls h-full font-pixel">{children}</body>
    </html>
  );
}
